# http://docs.travis-ci.com/user/languages/android/
language: android
android:
  components:
    - build-tools-22.0.0

os:
  - linux
  - osx

before_install:
  - export ANDROID_OS=$ANDROID_TARGET
  - if [ "$JRUBY_JARS_VERSION" == "MASTER" ] || [ "$JRUBY_JARS_VERSION" == "STABLE" ] ; then rake get_jruby_jars_snapshots ; fi
  - STABLE=`ls jruby-jars-*.gem | head -n 1 | cut -f 3 -d'-' | sed s/\\.gem//`
  - MASTER=`ls jruby-jars-*.gem | tail -n 1 | cut -f 3 -d'-' | sed s/\\.gem//`
  - if [ "$JRUBY_JARS_VERSION" == "MASTER" ] ; then export JRUBY_JARS_VERSION=$MASTER ; fi
  - if [ "$JRUBY_JARS_VERSION" == "STABLE" ] ; then export JRUBY_JARS_VERSION=$STABLE ; fi
  - which dd
  - which mkswap
  - which swapon
  - sudo dd if=/dev/zero of=/ruboto_swapfile bs=1024M count=16
  - sudo mkswap /ruboto_swapfile
  - sudo swapon /ruboto_swapfile

#after_test:
#  - sudo swapoff /swapfile
#  - sudo rm /swapfile

env:
  global:
    - DX_HEAP_SIZE=1536
    - RUBOTO_UPDATE_EXAMPLES=0
#    - RVM=2.1

  matrix:
    - ANDROID_TARGET=19 RUBOTO_PLATFORM=STANDALONE TEST_PART=1of5 JRUBY_JARS_VERSION=1.7.13
    - ANDROID_TARGET=19 RUBOTO_PLATFORM=STANDALONE TEST_PART=2of5 JRUBY_JARS_VERSION=1.7.13
    - ANDROID_TARGET=19 RUBOTO_PLATFORM=STANDALONE TEST_PART=3of5 JRUBY_JARS_VERSION=1.7.13
    - ANDROID_TARGET=19 RUBOTO_PLATFORM=STANDALONE TEST_PART=4of5 JRUBY_JARS_VERSION=1.7.13
    - ANDROID_TARGET=19 RUBOTO_PLATFORM=STANDALONE TEST_PART=5of5 JRUBY_JARS_VERSION=1.7.13
    - ANDROID_TARGET=19 RUBOTO_PLATFORM=STANDALONE TEST_PART=1of5 JRUBY_JARS_VERSION=1.7.16
    - ANDROID_TARGET=19 RUBOTO_PLATFORM=STANDALONE TEST_PART=2of5 JRUBY_JARS_VERSION=1.7.15
    - ANDROID_TARGET=19 RUBOTO_PLATFORM=FROM_GEM   TEST_PART=3of5 JRUBY_JARS_VERSION=1.7.13
    - ANDROID_TARGET=19 RUBOTO_PLATFORM=FROM_GEM   TEST_PART=4of5 JRUBY_JARS_VERSION=STABLE

    - ANDROID_TARGET=15 RUBOTO_PLATFORM=STANDALONE TEST_PART=2of5 JRUBY_JARS_VERSION=1.7.13
    - ANDROID_TARGET=15 RUBOTO_PLATFORM=STANDALONE TEST_PART=3of5 JRUBY_JARS_VERSION=1.7.13
    - ANDROID_TARGET=15 RUBOTO_PLATFORM=STANDALONE TEST_PART=4of5 JRUBY_JARS_VERSION=1.7.13
    - ANDROID_TARGET=15 RUBOTO_PLATFORM=STANDALONE TEST_PART=5of5 JRUBY_JARS_VERSION=1.7.13
    - ANDROID_TARGET=15 RUBOTO_PLATFORM=STANDALONE TEST_PART=1of5 JRUBY_JARS_VERSION=1.7.13
    - ANDROID_TARGET=15 RUBOTO_PLATFORM=STANDALONE TEST_PART=2of5 JRUBY_JARS_VERSION=1.7.16
    - ANDROID_TARGET=15 RUBOTO_PLATFORM=STANDALONE TEST_PART=3of5 JRUBY_JARS_VERSION=1.7.15
    - ANDROID_TARGET=15 RUBOTO_PLATFORM=FROM_GEM   TEST_PART=4of5 JRUBY_JARS_VERSION=1.7.13
    - ANDROID_TARGET=15 RUBOTO_PLATFORM=FROM_GEM   TEST_PART=5of5 JRUBY_JARS_VERSION=STABLE

matrix:
  fast_finish: true
  allow_failures:
    # Current master is failing: https://github.com/jruby/jruby/issues/1741
    # Current JRuby 1.7.x gem is failing.  Why?
    - env: ANDROID_TARGET=19 RUBOTO_PLATFORM=STANDALONE TEST_PART=1of5 JRUBY_JARS_VERSION=1.7.16
    - env: ANDROID_TARGET=19 RUBOTO_PLATFORM=STANDALONE TEST_PART=2of5 JRUBY_JARS_VERSION=1.7.15
    - env: ANDROID_TARGET=19 RUBOTO_PLATFORM=FROM_GEM   TEST_PART=4of5 JRUBY_JARS_VERSION=STABLE
    - env: ANDROID_TARGET=15 RUBOTO_PLATFORM=STANDALONE TEST_PART=2of5 JRUBY_JARS_VERSION=1.7.16
    - env: ANDROID_TARGET=15 RUBOTO_PLATFORM=STANDALONE TEST_PART=3of5 JRUBY_JARS_VERSION=1.7.15
    - env: ANDROID_TARGET=15 RUBOTO_PLATFORM=FROM_GEM   TEST_PART=5of5 JRUBY_JARS_VERSION=STABLE

script:
  - ./run_tests.sh

notifications:
  irc: "irc.freenode.org#ruboto"
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/fe0d532fe5bef5b7288c
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
